In [25]:
from sentence_transformers import SentenceTransformer
from sentence_transformers.models import Normalize

import pandas as pd

In [26]:
def read_best_scores(target_experiment: str):
    return pd.read_csv(f"../logs/{target_experiment}/best_scores.csv")

In [47]:
def get_similarity_to_best(df, model):
    df = df.reset_index()
    prompts = df["prompt"].tolist()
    best_prompt_idx = df["test_score"].idxmax()
    emb = model.encode(prompts)
    sim_scores = emb @ emb[best_prompt_idx].T

    df.loc[:, "sim_to_best"] = sim_scores
    return df

In [48]:
model = SentenceTransformer("sentence-transformers/all-MiniLM-L6-v2").append(Normalize())

In [49]:
df = read_best_scores("experiment_eval")

In [50]:
pd.set_option('display.max_colwidth', None)

In [51]:
df_ = df[df["task"]=="agnews"]
df_ = get_similarity_to_best(df_, model)
df_[["prompt", "test_score", "sim_to_best"]]

,prompt,test_score,sim_to_best
0,"Classify the topic of the following news as ""World"", ""Sports"", ""Tech"" or ""Business"".",0.890,1.000000
1,"Your task is to identify the subject of the news piece and classify it into one of four categories: World, Sports, Business and Tech.",0.875,0.852177
2,"The goal is to identify the journal article according to its primary theme and determine whether it belongs to the World, Sports, Business, or Tech category.</prompt",0.855,0.602846
3,"Choose a word from World, Sports, Business and Tech to categorize the given text.",0.850,0.755204
4,"Classify the media report into one of the below-listed sections: World, Sports, Business, or Tech, considering the main topic.",0.860,0.723024
5,"Give the main topic of the news article and then choose from World, Sports, Tech and Business.",0.855,0.748017
6,"Determine the primary subject of the provided news article and classify it under one of the following categories: World, Sports, Business, or Tech.",0.855,0.840707
7,"Determine the primary theme of a given news article and classify it under one of the four categories: World, Sports, Tech, or Business.",0.845,0.794006
8,"Determine the most suitable category (World, Sports, Business, or Tech) for a news article based on its dominant subject matter.",0.845,0.804505
9,"Your responsibility is to assign a news article to one of four categories: World, Sports, Business, or Tech, based on its main idea.",0.885,0.715320
10,"Classify a news article into one of four themed categories - World, Sports, Business, or Tech - based on its primary focus and emphasis.",0.885,0.798986
11,"Classify the given news article into one of four categories (World, Sports, Business, or Tech) based on its main theme or subject matter.",0.880,0.821221

In [53]:
df_ = df[df["task"]=="sst-5"]
df_ = get_similarity_to_best(df_, model)
df_[["prompt", "test_score", "sim_to_best"]].sort_values("sim_to_best", ascending=False)

,prompt,test_score,sim_to_best
10,"Classify the provided comment according to its sentiment intensity, assigning a label from ['terrible', 'bad', 'okay', 'good', 'great'] without providing additional context.",0.615,1.000000
11,"Identify the sentiment of the given text and categorize it as 'terrible', 'bad', 'okay', 'good', or 'great' based on its tone and language, outputting the corresponding sentiment label.",0.520,0.769955
6,"Determine the sentiment of the given text by labeling it as 'terrible', 'bad', 'okay', 'good', or 'great' according to the author's expressed emotions.",0.605,0.712387
7,"Assign a sentiment label ('terrible', 'bad', 'okay', 'good', or 'great') to the provided movie review, reflecting the overall emotional tone of the text.",0.560,0.700136
4,"Analyze the given text and assign it to one of the following categories: terrible, bad, okay, good, or great, considering the relevant context.",0.365,0.683417
2,"Analyze the sentence and categorize it into one of five categories based on the sentiment: terrible, bad, okay, good, or great.",0.560,0.676186
5,"Evaluate the text provided and categorize movie reviews into one of the following categories: terrible, bad, okay, good, or great.",0.470,0.654930
9,"Evaluate the emotional tone of the text and categorize it into one of five sentiment categories (terrible, bad, okay, good, or great) based on the presence of positive and negative sentiments, providing a precise and nuanced classification.",0.500,0.649835
1,"Classify the movie review provided to you into one of five categories based on the sentiment: terrible, bad, okay, good, or great.",0.505,0.637249
8,"Rate the emotional tone of the provided text as terrible, bad, okay, good, or great, reflecting the overall sentiment expressed.",0.570,0.632690
3,"Analyze the movie criticism provided to you into one of five categories based on the sentiment: terrible, bad, okay, good, or great, while considering the context and tone of the movie.",0.350,0.597581
0,"Based on the given movie review, rate it into one of five ratings based on the sentiment: terrible, bad, okay, good, or great.",0.560,0.569457